Business servlet
dallen68/PromoTube pull request #90
Opened 2020-07-22 17:37 UTC by dallen68

2020-07-22 19:31 UTC, josefj1519 requested changes

2020-07-22 19:31 UTC, josefj1519 commented on src/test/java/com/google/step/servlets/BusinessPromoCodeServletTest.java
> +}
new line

2020-07-22 19:31 UTC, josefj1519 commented on src/main/java/com/google/step/servlets/BusinessPromoCodeServlet.java
> +}
new line

2020-07-22 19:31 UTC, josefj1519 commented on src/main/java/com/google/step/servlets/ChannelPromoCodeServlet.java
> +@WebServlet("/channel/promo-code")
nit: maybe /channel/promo-code**s** would be a more appropriate URI since we are returning multiple promo-codes

2020-07-22 19:31 UTC, josefj1519 commented on src/main/java/com/google/step/servlets/BusinessPromoCodeServlet.java
> +@WebServlet("/business/promo-code")
/business/promo-code**s**

2020-07-22 20:10 UTC, josefj1519 approved these changes

2020-07-22 20:33 UTC, margaretchan approved these changes

2020-07-23 18:56 UTC, LiRq95 requested changes

2020-07-23 18:56 UTC, LiRq95 commented on src/test/java/com/google/step/servlets/BusinessPromoCodeServletTest.java
> +        StringWriter sw = new StringWriter();
There seems to be a few lines related to sw, pw and whens that gets repeated a lot, I'd probably put them in setup and have sw, pw be class variables just to make it concise.

2020-07-23 18:56 UTC, LiRq95 commented on src/test/java/com/google/step/servlets/BusinessPromoCodeServletTest.java
> +    public void promoCodesFromVideos() throws IOException {
A more descriptive test method name would be nice, something like promoCodesScrapedFromNonEmptyVideos to specify that videos did come up from the search.

2020-07-24 18:26 UTC, LiRq95 approved these changes

2020-07-24 18:31 UTC, merged